import type { Locale } from "@/i18n/config";
import {
  GOOGLE_FORM_NATIONALITIES,
  GOOGLE_FORM_NATIONALITY_OTHER,
} from "./welcome-nationalities";

/** ISO 3166-1 alpha-2 — chaves = valor PT enviado ao Google Forms. */
const COUNTRY_ISO: Record<string, string> = {
  Afeganistão: "AF",
  "África do Sul": "ZA",
  Albânia: "AL",
  Alemanha: "DE",
  Andorra: "AD",
  Angola: "AO",
  "Antígua e Barbuda": "AG",
  "Arábia Saudita": "SA",
  Argélia: "DZ",
  Argentina: "AR",
  Armênia: "AM",
  Austrália: "AU",
  Áustria: "AT",
  Azerbaijão: "AZ",
  Bahamas: "BS",
  Bangladesh: "BD",
  Barbados: "BB",
  Bahrein: "BH",
  Bélgica: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bielorrússia: "BY",
  Bolívia: "BO",
  "Bósnia e Herzegovina": "BA",
  Botsuana: "BW",
  Brasil: "BR",
  Brunei: "BN",
  Bulgária: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Butão: "BT",
  "Cabo Verde": "CV",
  Camarões: "CM",
  Camboja: "KH",
  Canadá: "CA",
  Catar: "QA",
  Cazaquistão: "KZ",
  Chade: "TD",
  Chile: "CL",
  China: "CN",
  Chipre: "CY",
  Colômbia: "CO",
  Comores: "KM",
  Congo: "CG",
  "Coreia do Norte": "KP",
  "Coreia do Sul": "KR",
  "Costa do Marfim": "CI",
  "Costa Rica": "CR",
  Croácia: "HR",
  Cuba: "CU",
  Dinamarca: "DK",
  Djibuti: "DJ",
  Dominica: "DM",
  Egito: "EG",
  "El Salvador": "SV",
  "Emirados Árabes Unidos": "AE",
  Equador: "EC",
  Eritreia: "ER",
  Eslováquia: "SK",
  Eslovênia: "SI",
  Espanha: "ES",
  "Estados Unidos": "US",
  Estônia: "EE",
  Essuatíni: "SZ",
  Etiópia: "ET",
  Fiji: "FJ",
  Filipinas: "PH",
  Finlândia: "FI",
  França: "FR",
  Gabão: "GA",
  Gâmbia: "GM",
  Gana: "GH",
  Geórgia: "GE",
  Granada: "GD",
  Grécia: "GR",
  Guatemala: "GT",
  Guiana: "GY",
  Guiné: "GN",
  "Guiné-Bissau": "GW",
  "Guiné Equatorial": "GQ",
  Haiti: "HT",
  Honduras: "HN",
  Hungria: "HU",
  Iêmen: "YE",
  "Ilhas Marshall": "MH",
  "Ilhas Salomão": "SB",
  Índia: "IN",
  Indonésia: "ID",
  Irã: "IR",
  Iraque: "IQ",
  Irlanda: "IE",
  Islândia: "IS",
  Israel: "IL",
  Itália: "IT",
  Jamaica: "JM",
  Japão: "JP",
  Jordânia: "JO",
  Kiribati: "KI",
  Kuwait: "KW",
  Laos: "LA",
  Lesoto: "LS",
  Letônia: "LV",
  Líbano: "LB",
  Libéria: "LR",
  Líbia: "LY",
  Liechtenstein: "LI",
  Lituânia: "LT",
  Luxemburgo: "LU",
  Madagascar: "MG",
  Malásia: "MY",
  Maláui: "MW",
  Maldivas: "MV",
  Mali: "ML",
  Malta: "MT",
  Marrocos: "MA",
  Maurício: "MU",
  Mauritânia: "MR",
  México: "MX",
  Micronésia: "FM",
  Moldávia: "MD",
  Mônaco: "MC",
  Mongólia: "MN",
  Montenegro: "ME",
  Moçambique: "MZ",
  Myanmar: "MM",
  Namíbia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Nicarágua: "NI",
  Níger: "NE",
  Nigéria: "NG",
  Noruega: "NO",
  "Nova Zelândia": "NZ",
  Omã: "OM",
  "Países Baixos": "NL",
  Palau: "PW",
  Palestina: "PS",
  Panamá: "PA",
  "Papua-Nova Guiné": "PG",
  Paquistão: "PK",
  Paraguai: "PY",
  Peru: "PE",
  Polônia: "PL",
  Portugal: "PT",
  Quênia: "KE",
  Quirguistão: "KG",
  "Reino Unido": "GB",
  "República Centro-Africana": "CF",
  "República Checa": "CZ",
  "República Democrática do Congo": "CD",
  "República Dominicana": "DO",
  Romênia: "RO",
  Ruanda: "RW",
  Rússia: "RU",
  Samoa: "WS",
  "San Marino": "SM",
  "Santa Lúcia": "LC",
  "São Cristóvão e Nevis": "KN",
  "São Tomé e Príncipe": "ST",
  "São Vicente e Granadinas": "VC",
  Seicheles: "SC",
  Senegal: "SN",
  "Serra Leoa": "SL",
  Sérvia: "RS",
  Singapura: "SG",
  Síria: "SY",
  Somália: "SO",
  "Sri Lanka": "LK",
  Sudão: "SD",
  "Sudão do Sul": "SS",
  Suécia: "SE",
  Suíça: "CH",
  Suriname: "SR",
  Tailândia: "TH",
  Tajiquistão: "TJ",
  Tanzânia: "TZ",
  "Timor-Leste": "TL",
  Togo: "TG",
  Tonga: "TO",
  "Trinidad e Tobago": "TT",
  Tunísia: "TN",
  Turcomenistão: "TM",
  Turquia: "TR",
  Tuvalu: "TV",
  Ucrânia: "UA",
  Uganda: "UG",
  Uruguai: "UY",
  Uzbequistão: "UZ",
  Vanuatu: "VU",
  Vaticano: "VA",
  Venezuela: "VE",
  Vietnã: "VN",
  Zâmbia: "ZM",
  Zimbábue: "ZW",
};

const LOCALE_TO_INTL: Record<Locale, string> = {
  pt: "pt-BR",
  es: "es",
  fr: "fr",
  en: "en",
};

const otherLabels: Record<Locale, string> = {
  pt: "Outro",
  es: "Otro",
  fr: "Autre",
  en: "Other",
};

let displayNamesCache: Partial<Record<Locale, Intl.DisplayNames>> = {};

function getDisplayNames(locale: Locale): Intl.DisplayNames | undefined {
  if (displayNamesCache[locale]) return displayNamesCache[locale];
  try {
    const dn = new Intl.DisplayNames([LOCALE_TO_INTL[locale]], { type: "region" });
    displayNamesCache[locale] = dn;
    return dn;
  } catch {
    return undefined;
  }
}

/** Rótulo localizado para exibição; valor enviado ao Forms permanece em PT. */
export function getNationalityLabel(
  locale: Locale,
  formValue: string,
): string {
  if (formValue === GOOGLE_FORM_NATIONALITY_OTHER) {
    return otherLabels[locale];
  }
  if (locale === "pt") return formValue;

  const iso = COUNTRY_ISO[formValue];
  if (iso) {
    const label = getDisplayNames(locale)?.of(iso);
    if (label) return label;
  }
  return formValue;
}

export { GOOGLE_FORM_NATIONALITIES };
