/**
 * Países / nacionalidades no formulário de cadastro (lista completa, ordem alfabética PT).
 *
 * Os VALORES são enviados ao Google Forms e devem ser idênticos às opções
 * do dropdown "País" no formulário Google. Replique esta lista lá.
 */
export const GOOGLE_FORM_NATIONALITIES = [
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Antígua e Barbuda",
  "Arábia Saudita",
  "Argélia",
  "Argentina",
  "Armênia",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Bahrein",
  "Bélgica",
  "Belize",
  "Benin",
  "Bielorrússia",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Butão",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Colômbia",
  "Comores",
  "Congo",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "Djibuti",
  "Dominica",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritreia",
  "Eslováquia",
  "Eslovênia",
  "Espanha",
  "Estados Unidos",
  "Estônia",
  "Essuatíni",
  "Etiópia",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Gana",
  "Geórgia",
  "Granada",
  "Grécia",
  "Guatemala",
  "Guiana",
  "Guiné",
  "Guiné-Bissau",
  "Guiné Equatorial",
  "Haiti",
  "Honduras",
  "Hungria",
  "Iêmen",
  "Ilhas Marshall",
  "Ilhas Salomão",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jordânia",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letônia",
  "Líbano",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Madagascar",
  "Malásia",
  "Maláui",
  "Maldivas",
  "Mali",
  "Malta",
  "Marrocos",
  "Maurício",
  "Mauritânia",
  "México",
  "Micronésia",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Moçambique",
  "Myanmar",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Noruega",
  "Nova Zelândia",
  "Omã",
  "Países Baixos",
  "Palau",
  "Palestina",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polônia",
  "Portugal",
  "Quênia",
  "Quirguistão",
  "Reino Unido",
  "República Centro-Africana",
  "República Checa",
  "República Democrática do Congo",
  "República Dominicana",
  "Romênia",
  "Ruanda",
  "Rússia",
  "Samoa",
  "San Marino",
  "Santa Lúcia",
  "São Cristóvão e Nevis",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Seicheles",
  "Senegal",
  "Serra Leoa",
  "Sérvia",
  "Singapura",
  "Síria",
  "Somália",
  "Sri Lanka",
  "Sudão",
  "Sudão do Sul",
  "Suécia",
  "Suíça",
  "Suriname",
  "Tailândia",
  "Tajiquistão",
  "Tanzânia",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad e Tobago",
  "Tunísia",
  "Turcomenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietnã",
  "Zâmbia",
  "Zimbábue",
  "Outro",
] as const;

export type GoogleFormNationality =
  (typeof GOOGLE_FORM_NATIONALITIES)[number];

export const GOOGLE_FORM_NATIONALITY_OTHER = "Outro" as const satisfies GoogleFormNationality;

