-- Sub-trilhas (tópicos) dentro de cada módulo.
-- Permite que um módulo seja um hub que agrupa vários sub-conteúdos focados,
-- cada um com sua própria página e seus próprios contatos relacionados.

create table topics (
  id           bigint generated by default as identity primary key,
  module_id    bigint not null references modules(id) on delete cascade,
  slug         text not null,
  order_index  int not null default 0,
  published    boolean not null default true,
  created_at   timestamptz not null default now(),
  unique (module_id, slug)
);

create table topic_translations (
  topic_id       bigint not null references topics(id) on delete cascade,
  locale         locale not null,
  title          text not null,
  summary        text not null,
  body_markdown  text not null,
  primary key (topic_id, locale)
);

create table topic_contacts (
  topic_id    bigint not null references topics(id) on delete cascade,
  contact_id  bigint not null references contacts(id) on delete cascade,
  primary key (topic_id, contact_id)
);

create index topics_module_idx on topics(module_id, order_index);

-- ------------------------------------------------------------
-- Row Level Security (mesmo padrão das tabelas de conteúdo).
-- ------------------------------------------------------------

alter table topics              enable row level security;
alter table topic_translations  enable row level security;
alter table topic_contacts      enable row level security;

create policy "Public read topics" on topics
  for select using (
    published = true
    and exists (
      select 1 from modules m
      where m.id = topics.module_id
        and (m.published or public.is_admin())
    )
    or public.is_admin()
  );

create policy "Public read topic translations" on topic_translations
  for select using (
    exists (
      select 1 from topics t
      where t.id = topic_translations.topic_id
        and (t.published or public.is_admin())
    )
  );

create policy "Public read topic contacts" on topic_contacts for select using (true);

create policy "Admin write topics" on topics
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write topic translations" on topic_translations
  for all using (public.is_admin()) with check (public.is_admin());
create policy "Admin write topic contacts" on topic_contacts
  for all using (public.is_admin()) with check (public.is_admin());
